/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#a8afff',
        'surface-bright': '#31394d',
        'outline': '#8e90a2',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#002ccd',
        'surface': '#0b1326',
        'surface-container': '#171f33',
        'on-secondary': '#1b247f',
        'on-tertiary-fixed-variant': '#004f58',
        'error-container': '#93000a',
        'primary-fixed': '#dee0ff',
        'on-secondary-fixed-variant': '#343d96',
        'inverse-primary': '#2848ee',
        'inverse-on-surface': '#283044',
        'tertiary': '#00daf3',
        'on-primary-fixed': '#000f5d',
        'primary': '#bbc3ff',
        'surface-container-high': '#222a3d',
        'surface-container-low': '#131b2e',
        'primary-container': '#3c59fd',
        'background': '#0b1326',
        'secondary-fixed-dim': '#bdc2ff',
        'primary-fixed-dim': '#bbc3ff',
        'secondary': '#bdc2ff',
        'surface-container-lowest': '#060e20',
        'on-tertiary-container': '#cef7ff',
        'on-primary': '#001d93',
        'on-surface-variant': '#c4c5d9',
        'on-secondary-fixed': '#000767',
        'on-tertiary-fixed': '#001f24',
        'outline-variant': '#434656',
        'on-tertiary': '#00363d',
        'surface-variant': '#2d3449',
        'tertiary-fixed-dim': '#00daf3',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#e0e0ff',
        'on-background': '#dae2fd',
        'secondary-container': '#343d96',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'inverse-surface': '#dae2fd',
        'surface-tint': '#bbc3ff',
        'on-primary-container': '#f0efff',
        'tertiary-container': '#007886',
        'error': '#ffb4ab',
        'surface-dim': '#0b1326',
        'tertiary-fixed': '#9cf0ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      keyframes: {
        navEnter: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        heroFadeUp: {
          '0%': { opacity: '0', transform: 'translateY(15px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        ambientShift: {
          '0%, 100%': { backgroundPosition: '50% 0%' },
          '50%': { backgroundPosition: '50% 30%' },
        },
        popScale: {
          '0%': { opacity: '0', transform: 'scale(0.8)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        iconRotate: {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(15deg)' },
        },
      },
      animation: {
        navEnter: 'navEnter 400ms cubic-bezier(0.165, 0.84, 0.44, 1) both',
        heroFadeUp: 'heroFadeUp 500ms cubic-bezier(0.165, 0.84, 0.44, 1) both',
        ambientShift: 'ambientShift 25s ease-in-out infinite',
        popScale: 'popScale 400ms cubic-bezier(0.165, 0.84, 0.44, 1) both',
        iconRotate: 'iconRotate 300ms cubic-bezier(0.165, 0.84, 0.44, 1) forwards',
      },
    },
  },
  plugins: [],
}

